name: Black

on:
  push:
    branches-ignore: [main]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install black

      - run: black .

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: format with black"
